/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_stay_gif_GifEncoder */

#ifndef _Included_com_stay_gif_GifEncoder
#define _Included_com_stay_gif_GifEncoder
#ifdef __cplusplus
extern "C" {
#endif
#undef com_stay_gif_GifEncoder_COLOR
#define com_stay_gif_GifEncoder_COLOR 256L
#undef com_stay_gif_GifEncoder_QUALITY
#define com_stay_gif_GifEncoder_QUALITY 10L
/*
 * Class:     com_stay_gif_GifEncoder
 * Method:    addFrame
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_com_stay_gif_GifEncoder_addFrame
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_stay_gif_GifEncoder
 * Method:    init
 * Signature: (Ljava/lang/String;IIIII)I
 */
JNIEXPORT jint JNICALL Java_com_stay_gif_GifEncoder_init
  (JNIEnv *, jobject, jstring, jint, jint, jint, jint, jint);

/*
 * Class:     com_stay_gif_GifEncoder
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_stay_gif_GifEncoder_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
